name: Reusable workflow to build LaTeX document

on:
  workflow_call:
    inputs:
      document:
        description: "The name of the LaTeX document to build, without the .tex extension"
        required: true
        type: string
      diff:
        description: "Whether to compile the diff between the document in the commit and in the base branch"
        required: false
        default: false
        type: boolean
      working_directory:
        description: "The directory where the LaTeX document is located, relative to the root of the repository"
        required: false
        default: "."
        type: string
      texlive_version:
        description: "The version of TeX Live to use to build the document"
        required: false
        default: "latest"
        type: string
      latexmk_use_xelatex:
        description: "Whether to use XeLaTeX instead of PDFLaTeX to build the document"
        required: false
        default: false
        type: boolean
      latexmk_use_lualatex:
        description: "Whether to use LuaLaTeX instead of PDFLaTeX to build the document"
        required: false
        default: false
        type: boolean

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Download LaTeX styles
        run: |
          curl -OL https://github.com/dpo/latex-styles/archive/refs/heads/master.zip
          unzip master.zip
      - name: Compute name of document to compile
        id: computeDocumentName
        run: |
          pre_compile0="git config --global --add safe.directory /github/workspace"
          if [ "${{ inputs.diff }}" = "true" ]; then
            echo "pre_compile=$pre_compile0 && latexdiff-vc --git --flatten --disable-auto-mbox --exclude-safecmd='Cref,Cref\*,hspace' --allow-spaces --no-links -r ${{ github.event.pull_request.base.sha }} ${{ inputs.document }}.tex" >> GITHUB_OUTPUT
            echo "document_name=${{ inputs.document }}-diff${{ github.event.pull_request.base.sha }}" >> $GITHUB_OUTPUT
          else
          echo "pre_compile=$pre_compile0" >> $GITHUB_OUTPUT
            echo "document_name=${{ inputs.document }}" >> $GITHUB_OUTPUT
          fi
      - name: Compile LaTeX document
        id: compileLaTeXdocument
        uses: xu-cheng/latex-action@v4
        with:
          texlive_version: ${{ inputs.texlive_version }}
          root_file: ${{ steps.computeDocumentName.outputs.document_name }}.tex
          working_directory: ${{ inputs.working_directory }}
          extra_system_packages: "git patch"
          latexmk_shell_escape: true
          latexmk_use_xelatex: ${{ inputs.latexmk_use_xelatex }}
          latexmk_use_lualatex: ${{ inputs.latexmk_use_lualatex }}
          pre_compile: ${{ steps.computeDocumentName.outputs.pre_compile }}
        env:
          TEXINPUTS: ".:$PWD/../latex-styles-master/styles//:"
          BSTINPUTS: ".:$PWD/../latex-styles-master/styles/common"
          BIBINPUTS: ".:$PWD/../latex-styles-master/share"
        continue-on-error: true
      - name: Upload PDF
        if: steps.compileLaTeXdocument.outcome == 'success'
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.computeDocumentName.outputs.document_name }}-pdf
          path: ${{ inputs.working_directory }}/${{ steps.computeDocumentName.outputs.document_name }}.pdf
      - name: Upload build logs
        if: steps.compileLaTeXdocument.outcome == 'failure'
        uses: actions/upload-artifact@v7
        with:
          name: ${{ inputs.document }}-logs
          path: |
            paper/**/*.log
      - name: Fail job if build failed
        if: steps.compileLaTeXdocument.outcome == 'failure'
        run: exit 1
