name: Reusable workflow to create a release with PDF assets

on:
  workflow_call:
    inputs:
      files:
        description: "The names of the PDF documents to upload as assets, without the .pdf extension"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
      - name: Create release
        uses: rymndhng/release-on-push-action@master
        id: release
        with:
          # add a label to your pull request to change the default behavior:
          # release:major
          # release:minor
          # release:patch
          # norelease
          bump_version_scheme: patch
          tag_prefix: v
          release_body: ""
          use_github_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.release.outputs.tag_name }}
          files: |
            ${{ inputs.files }}
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
